function currentYPosition(){if(self.pageYOffset)return self.pageYOffset;if(document.documentElement&&document.documentElement.scrollTop)
return document.documentElement.scrollTop;if(document.body.scrollTop)return document.body.scrollTop;return 0}
function cword(s){s=s.replace(/(?:\r\n|\r|\n)/g,' ');s=s.replace(/[^a-zA-ZА-Яа-яЁё0-9\s]/gi,"");s=s.replace(/(^\s*)|(\s*$)/gi,"");s=s.replace(/[ ]{2,}/gi," ");s=s.replace(/\n /,"\n");return s.split(' ').filter(function(str){return str!=""}).length}
let $inputVal=1,$boundingClientRect=[],$resizeTimeout;jQuery(document).ready(function($){const urlParams=new URLSearchParams(window.location.search),discount=urlParams.get('discount'),need=urlParams.get('need'),wpnonce=urlParams.get('wpnonce'),discount_url=urlParams.get('url');$(window).load(function(){let $select=$('.variations select');if($select.length>0){$select.trigger('change')}});$(document).on({mouseenter:function(){if(!$(document.body).hasClass('mobile-browser')&&!$(document.body).hasClass('ie-mobile')&&!$(document.body).hasClass('apple-mobile-browser')){$(document.body).addClass('body-stop')}},mouseleave:function(){$(document.body).removeClass('body-stop')}},'ul.sub-menu, .multiselect-button .options');if(typeof ajaxurl!='undefined'&&discount&&need=='ajax'&&wpnonce){$.ajax({url:ajaxurl,global:!1,dataType:'json',method:'post',data:{discount:discount,wpnonce:wpnonce,action:'urlApplyCoupon',url:discount_url,},success:function(response){if(response.success){window.location.href=response.data.redirect}},error:function(){alert("Not found Data")}})}
let $lost_password=$('.woocommerce-LostPassword.lost_password a');if($lost_password.length>0){const $lost_url=new URL($lost_password.attr('href'));$('#username').on('keyup',function(){let $this=$(this);$lost_password.attr('href',$lost_url.pathname+'?email='+$this.val())})}
$('#affwp-generate-ref-url').submit(function(){setTimeout(function(){let $affwp_url=$('#affwp-referral-url').val();$.get($affwp_url,function(data){}).done(function(){}).fail(function(){$('.affwp-wrap.affwp-base-url-wrap').find('.affwp-errors').remove();$('.affwp-wrap.affwp-base-url-wrap').append('<div class="affwp-errors"><p class="affwp-error">'+$affwp_url+'</p></div>')})},100);return!1});function replaceCurrencySymbolByCountry(selector){var $element=typeof selector!=='undefined'?jQuery(selector):jQuery('body'),$priceAmount;if(cloudFlareGeoIp.getCountry()!=='US'){$element.find('.woocommerce-Price-amount .woocommerce-Price-currencySymbol').text('US$');$priceAmount=$element.find('.woocommerce-Price-amount').not(':has(.woocommerce-Price-currencySymbol)');$priceAmount.text($priceAmount.text().replace(/^\$/,'US$'))}}
cloudFlareGeoIp.onInit(function(){localStorage.setItem('shipping_widget_country_my',cloudFlareGeoIp.getCountry());replaceCurrencySymbolByCountry();jQuery(document).ajaxComplete(function(){if(jQuery('#jckqv').length!==0){replaceCurrencySymbolByCountry('#jckqv')}});jQuery(document.body).on('updated_checkout updated_wc_div wc_fragments_refreshed',function(){replaceCurrencySymbolByCountry()});if(typeof wc_add_to_cart_variation_params!=='undefined'){let $variationForm=jQuery('form.variations_form.cart'),$price=jQuery('.product-price-wrap h3.price'),$variation=jQuery('.single_variation_wrap .single_variation'),$customVariation=jQuery('.product-price-wrap .custom_single_variation');function duplicateVariationSection(variation){$price.hide();$customVariation.empty();$variation.children().each(function(){$customVariation.append(jQuery(this).clone(!0,!0))});if((typeof variation!=='undefined'&&typeof variation.is_in_stock!=='undefined'&&variation.is_in_stock===!1)||$variation.find('.woocommerce-variation-availability > .out-of-stock').length>0){jQuery('#rp_wcdpd_pricing_table_variation_container').hide()}else{jQuery('#rp_wcdpd_pricing_table_variation_container').show()}
$customVariation.show();replaceCurrencySymbolByCountry($customVariation)}
if(cloudFlareGeoIp.getCountry()!=='US'){var inselect_prices=$variationForm.find('.variations select'),f_inselect_prices=function(){if(inselect_prices.length===1){inselect_prices.find('option').each(function(i,v){let opt=jQuery(v),opt_t=opt.text();if(!opt_t.includes('US')){opt.text(opt_t.replace('$','US$'))}})}};f_inselect_prices()}
if($variation.children().length>0){duplicateVariationSection()}
$variationForm.on('show_variation',function(e,variation){duplicateVariationSection(variation)}).on('reset_data',function(){$price.show();$customVariation.hide();if(cloudFlareGeoIp.getCountry()!=='US'){f_inselect_prices()}})}});jQuery('body.single-product form.cart input.qty').on('change',function(){var $input=jQuery(this),qty=parseInt($input.val(),10),min=parseInt($input.attr('min'),10),max=parseInt($input.attr('max'),10);if(qty<min){$input.val(min)}else if(qty>max){$input.val(max)}});jQuery('.payments-faqs ul li').off('click').click(function(e){e.preventDefault();if($(this).hasClass('active')==!1){var activeData=$('.payments-faqs section[data-id='+$('.payments-faqs ul li.active').data('id')+']');var id=$(this).data('id');var link=$(this).data('link');var _this=$(this);var args={'action':'change_payment_question','id':id};if($('.payments-faqs section[data-id='+id+']').length>0){$('.payments-faqs').find('section.info').each(function(){if($(this).data('id')!=id){$(this).hide()}else{$(this).fadeIn(250)}});$('.payments-faqs ul li.active').removeClass('active');_this.addClass('active');activeData=$('.payments-faqs section[data-id='+$('.payments-faqs ul li.active').data('id')+']');document.title=activeData.find('h1').text();history.pushState(null,null,link)}else if(_this.attr("disabled")!=='disabled'){_this.attr("disabled",!0);activeData.addClass('loader');$.ajax({url:ajaxurl,global:!1,dataType:'json',method:'post',data:args,success:function(response){if(typeof response.success!=="undefined"&&response.success==!0){$('.payments-faqs').append(response.data.html);$('.payments-faqs').find('section.info').each(function(){if($(this).data('id')!=id){$(this).hide()}else{$(this).fadeIn(250,function(){activeData.removeClass('loader')})}});$('.payments-faqs ul li.active').removeClass('active');_this.addClass('active');document.title=response.data.title;history.pushState(null,null,link)}else{alert("Not found Data")}
_this.attr("disabled",!1)},error:function(){alert("Not found Data");_this.attr("disabled",!1)}})}}});cloudFlareGeoIp.onInit(function(){localStorage.setItem('shipping_widget_country',cloudFlareGeoIp.getCountry());jQuery('.free-shipping-default, .free-shipping-non-usa, .free-shipping-usa').hide();if(cloudFlareGeoIp.getCountry()!=='US'){jQuery('.free-shipping-non-usa').show()}else{jQuery('.free-shipping-usa').show()}
jQuery('.global-widget-banner').css('opacity','1')});jQuery("#footer .widget_nav_menu .menu-item-has-children").each(function(){jQuery(this).append('<span class="plus"><i class="fa fa-chevron-down" aria-hidden="true"></i></spa>')});jQuery("#footer .widget_nav_menu .menu-item-has-children").on("click",'span, > a',function(e){let $width=jQuery(window).width();if($width<768){let $this=jQuery(this),$parent=$this.parent(),$arrow=$this.siblings('span');if($this.is('a')){$arrow=$this.siblings('span')}else{$arrow=$this}
$parent.toggleClass('active');$arrow.html($arrow.find('i').hasClass('fa-chevron-down')?'<i class="fa fa-chevron-up" aria-hidden="true"></i>':'<i class="fa fa-chevron-down" aria-hidden="true"></i>')}});jQuery('#icustombilling_gate_card_number').attr('placeholder','Card Number');jQuery('.checkout_coupon').prepend('<h3>Apply Store Credit or Promotional Coupons</h3>');jQuery('#account_password_field label').html('Set password <abbr class="required" title="required">*</abbr>');var isSafari=/constructor/i.test(window.HTMLElement)||(function(p){return p.toString()==="[object SafariRemoteNotification]"})(!window.safari||safari.pushNotification);var isIE=!1||!!document.documentMode;if(typeof wc_customer_data.user_id=='undefined'){var guestData='';if(isSafari||isIE){guestData=localStorage.getItem('guestData')}else{guestData=getCookie('guestData')}
var fieldsArr=['billing_first_name','billing_last_name','billing_company','billing_email','billing_phone','billing_address_1','billing_address_2','billing_city','billing_state','billing_postcode','billing_country'];if((typeof guestData!='undefined')&&(guestData!=null)){guestData=JSON.parse(guestData);if(typeof guestData=='object'){fieldsArr.forEach(function(currentValue,index){if(guestData.hasOwnProperty(currentValue)){jQuery('#customer_details .woocommerce-billing-fields').find('[name="'+currentValue+'"]').val(guestData[currentValue])}})}}
jQuery('form[name="checkout"] .woocommerce-billing-fields input').on('focusout',function(){guestData={};fieldsArr.forEach(function(currentValue,index){var fieldVal=jQuery('#customer_details .woocommerce-billing-fields').find('[name="'+currentValue+'"]').val();guestData[currentValue]=fieldVal});guestData=JSON.stringify(guestData);if(isSafari||isIE){localStorage.setItem('guestData',guestData)}else{document.cookie="guestData="+guestData}})}
setTimeout(function(){if(jQuery('.woocommerce-billing-fields .details_billing').css('display')=='none'){jQuery('#billing_address_not_found').trigger('click')}},3000);var cardsDataObj={};jQuery('body').on('updated_checkout',function(){var paymentMethod=jQuery('.woocommerce-checkout-payment input:checked').attr('id');var paymentBlock=jQuery('.woocommerce-checkout-payment li.'+paymentMethod);var paymentFields=jQuery(paymentBlock).find('input:not([type="submit"]):not(#'+paymentMethod+'), select');if(typeof cardsDataObj[paymentMethod]=='undefined'){cardsDataObj[paymentMethod]={}}else{for(var key in cardsDataObj[paymentMethod]){if(cardsDataObj[paymentMethod].hasOwnProperty(key)){jQuery(paymentBlock).find('[name="'+key+'"]').val(cardsDataObj[paymentMethod][key])}}}
if(paymentFields.length>0){(function(gatewayEntries){var keys={input:'',select:'',};for(var i=0;i<=gatewayEntries.length-1;i++){if(gatewayEntries[i].type=='text'){keys.input+='input[name="'+gatewayEntries[i].name+'"]';if(i<gatewayEntries.length){keys.input+=','}}else if(gatewayEntries[i].type=='select-one'){keys.select+='select[name="'+gatewayEntries[i].name+'"]';if(i<gatewayEntries.length){keys.select+=','}}
if(typeof cardsDataObj[paymentMethod][gatewayEntries[i].name]=='undefined'||cardsDataObj[paymentMethod][gatewayEntries[i].name]==''){cardsDataObj[paymentMethod][gatewayEntries[i].name]=gatewayEntries[i].value}}
if(keys.input.substring(keys.input.length-1)==','){keys.input=keys.input.substring(0,keys.input.length-1)}
if(keys.select.substring(keys.select.length-1)==','){keys.select=keys.select.substring(0,keys.select.length-1)}
jQuery('#order_review').on('blur',keys.input,function(e){if(typeof e.currentTarget.value!='undefined'){cardsDataObj[paymentMethod][e.currentTarget.name]=e.currentTarget.value}});jQuery('#order_review').on('change',keys.select,function(e){if(typeof e.currentTarget.value!='undefined'){cardsDataObj[paymentMethod][e.currentTarget.name]=e.currentTarget.value}})})(paymentFields)}});var urlString=window.location.href;if(urlString.indexOf('/p2p-payment-faq/')!==-1){var getOrderNumber=getUrlParameterByName('order_number');var getOrderTotal=getUrlParameterByName('order_total');if(getOrderNumber!==null&&getOrderTotal!==null){document.body.innerHTML=document.body.innerHTML.replace(/{order_number}/g,getOrderNumber);document.body.innerHTML=document.body.innerHTML.replace(/{order_total}/g,getOrderTotal)}
var randomWords=['dinner','concert','groceries','restaurant','uber','tickets','gas','ride','suite','breakfast','furniture','meal','lunch','game','snacks','dancing','clothes','sushi','supplies','adventures','food','lyft','taxi','night','celebration','life','uber','eats','gifts','board','studio','market','banquet','house','party','snacks'];document.body.innerHTML=document.body.innerHTML.replace(/dinner/g,randomWords[Math.floor(Math.random()*randomWords.length)])}else if(urlString.indexOf('/approval-application-submission/')!==-1){$('#gform_1 #field_1_10 .gfield_description:first').append('<p style="margin-bottom: 0 !important; font-size: 1.01em; line-height: 1;">Word count: (<span id="intended-use-counter">0</span>)</p>');let $field=$('#gform_1 #input_1_10'),text=$field.val().toString();$('#intended-use-counter').text(cword(text));$field.on('keyup paste blur',function(){let text=$(this).val().toString();$('#intended-use-counter').text(cword(text))})}
let $wc_category_count_el=$('.woocommerce-shop-page .woocommerce-count-wrap .woocommerce-result-count:not(.for-articles)');if($wc_category_count_el.length>0){let wc_category_count=$wc_category_count_el.html(),wc_category_count_short=wc_category_count.replace('Showing ','')}
$(window).on('load resize orientationchange',function(){if($wc_category_count_el.length>0){let win_width=$(window).width();if(win_width<479){if(typeof wc_category_count_short!='undefined'){$wc_category_count_el.html(wc_category_count_short)}}else{if(typeof wc_category_count!='undefined'){$wc_category_count_el.html(wc_category_count)}}}})});var times=1;jQuery(document).on('blur','#billing_address_google_field input',function(){if(times<2){times=times+1;jQuery('.details_billing').slideDown()}});function getUrlParameterByName(name,url){if(!url)url=window.location.href;name=name.replace(/[\[\]]/g,"\\$&");var regex=new RegExp("[?&]"+name+"(=([^&#]*)|&|#|$)"),results=regex.exec(url);if(!results)return null;if(!results[2])return'';return decodeURIComponent(results[2].replace(/\+/g," "))}
function getCookie(name){var matches=document.cookie.match(new RegExp("(?:^|; )"+name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,'\\$1')+"=([^;]*)"));return matches?decodeURIComponent(matches[1]):undefined}
function whenThen(conditionFunc,intervalInMs,successFunc){var rounds=0;var timer=setInterval(function(){rounds++;if(conditionFunc()){clearInterval(timer);successFunc()}
if(rounds>3){clearInterval(timer)}},intervalInMs)}
function googleAnalyticsIntegration(){var mfSessionId=mouseflow.getSessionId();if(mfSessionId){ga('set','dimension1',mfSessionId);ga('send','event','Mouseflow',mfSessionId,{nonInteraction:!0})}}jQuery(function($){var product_gallery=$('.woocommerce-product-gallery'),firstRun=!0,variationClassesAdded=!1;function setVariationThumbsClasses(){if(!variationClassesAdded&&$('.flex-control-thumbs li').length){clearInterval(flexThumbsCheckInterval);$('.woocommerce-product-gallery__image.variation-image').each(function(){let $this=$(this);let ind=$this.index();$('.flex-control-thumbs li').eq(ind).addClass('variation-thumb variation-thumb-'+$this.data('varid')).hide()});variationClassesAdded=!0}}
let flexThumbsCheckInterval=setInterval(setVariationThumbsClasses,300);$('body').on('show_variation',function(event,variation){if(!firstRun){product_gallery.block({message:null,overlayCSS:{background:'#fff',opacity:0.6}})}else{setVariationThumbsClasses();firstRun=!1}
let thumbs=$('.flex-control-thumbs');if(thumbs.find('li.variation-thumb-'+variation.variation_id).length>0){thumbs.find('li:not(.variation-thumb):not(:first-child)').hide()}else{thumbs.find('li:not(.variation-thumb)').show()}
thumbs.find('li.variation-thumb').hide().filter('.variation-thumb-'+variation.variation_id).show();thumbs.find('li img').removeClass('clicked');thumbs.find('li:first-child img').addClass('clicked')}).on('reset_data',function(){product_gallery.block({message:null,overlayCSS:{background:'#fff',opacity:0.6}});let thumbs=jQuery('.flex-control-thumbs');thumbs.find('li.variation-thumb').hide();thumbs.find('li:not(.variation-thumb)').show();thumbs.find('li img').removeClass('clicked');thumbs.find('li:first-child img').addClass('clicked')});$('.variations_form').on('woocommerce_variation_has_changed hide_variation',function(){setTimeout(function(){product_gallery.unblock()},300)});addNameAttrToHeaders();$(window).load(function(){if(window.location.hash){let $hash=window.location.hash;if($hash){$hash=$hash.slice(1);let $element=$('[name='+$hash+']');if($element.length>0){let $header=$('#mobile-header').outerHeight(!0);$('html, body').scrollTop(($element.get(0).getBoundingClientRect().top+currentYPosition())-parseInt($header)-10)}}}});$(document.body).on("woocommerce_variation_has_changed",function(){$('.product-price-wrap .buy_more_text').remove();let $form=$('form[data-product_variations]'),$variation_id=$form.find('input[name="variation_id"], input.variation_id').val(),$single=$('.custom_single_variation'),$text=$('.buy_more_text'),$data=JSON.parse($form.attr('data-product_variations')),$quantity=$form.find('input[name=quantity]'),$button=$form.find('button'),$notice=$('.woocommerce-error');if($notice.length>0){$notice.remove()}
if($button.length>0){$button.data('quantity',$quantity.val()).attr('data-quantity',$quantity.val())}
if($data.length){$data.forEach(function($item){if($item.variation_id==$variation_id){window.history.pushState("","",window.location.origin+window.location.pathname+'?'+$.param($item.attributes))}})}
if($text.length>0){let $clone=$text.clone(),$json=$clone.children('.variable-mix').data('json');if(typeof $json[$variation_id]!='undefined'){$json[$variation_id]=cloudFlareGeoIp.getCountry()!=='US'?$json[$variation_id].replace(/^\$/,'US$').replace(/&#36;/,'US$'):$json[$variation_id];$clone.children('.variable-mix').html($json[$variation_id]);$clone.removeClass('with-variation');$single.append($clone)}else if($variation_id===''&&typeof $json.min!=='undefined'){$json.min=cloudFlareGeoIp.getCountry()!=='US'?$json.min.replace(/^\$/,'US$').replace(/&#36;/,'US$'):$json.min;if(typeof $json.max!=='undefined'){$json.max=cloudFlareGeoIp.getCountry()!=='US'?$json.max.replace(/^\$/,'US$').replace(/&#36;/,'US$'):$json.max;let minValue=parseFloat($json.min.replace(/[^0-9,.]/g,'').replace(',','.')),maxValue=parseFloat($json.max.replace(/[^0-9,.]/g,'').replace(',','.'));if(minValue!==maxValue){$clone.children('.variable-mix').html($json.min+' - '+$json.max)}else{$clone.children('.variable-mix').html($json.min)}}else{$clone.children('.variable-mix').html($json.min)}
$clone.removeClass('with-variation');$clone.css('width','100%');$('.product-price-wrap .price').css('margin-bottom','14px');$('.product-price-wrap').append($clone);$('.single_variation_wrap').find('.quantity').show();$('.single_variation_wrap').find('button').show();$('.single_variation_wrap').find('a.button').css('margin-left','')}}
$('.info_content .info_block').addClass('hidden');const labelClass=$variation_id?'.info_content .info_block[data-variation-id="'+$variation_id+'"]':'.info_content .info_block:first-child';$(labelClass).removeClass('hidden')});$(document.body).on("check_variations",function(){cloudFlareGeoIp.onInit(function(){let $form=$('form[data-product_variations]');if($form.length>0){let $data=JSON.parse($form.attr('data-product_variations')),$replace=cloudFlareGeoIp.getCountry()!=='US'?'US$':'$',$attr=[],defaultNameFormat='{name} - {price}',attributeNameFormat={};for(let keys in $data){if(typeof $data[keys].attributes!=='undefined'){for(let key in $data[keys].attributes){$attr[$data[keys].attributes[key]]={price:($data[keys].price_html?$($data[keys].price_html).find('.woocommerce-Price-currencySymbol').text():$replace)+$data[keys].display_price,stock_status:$data[keys].stock_status_text,is_discontinued:$data[keys].is_discontinued}}
if(typeof $data[keys].attribute_name_format!=='undefined'&&$data[keys].attribute_name_format){attributeNameFormat=$data[keys].attribute_name_format}}}
$('.variations .value select').each(function(){let attributeName=$(this).data('attribute_name').replace('attribute_',''),format=typeof attributeNameFormat[attributeName]!=='undefined'&&attributeNameFormat[attributeName]?attributeNameFormat[attributeName]:defaultNameFormat;$(this).find('option').each(function(){let $option=$(this),$val=$option.val();if($val&&typeof $attr[$val]!=='undefined'){let $title=$option.data('original_title');if(!$title){$title=$option.text();$option.data('original_title',$title)}
$title=format.replace('{name}',$title);$title=$title.replace('{price}',$attr[$val].price+$attr[$val].stock_status);$option.text($title.replace(/\s\s+/g,' ').trim());if($attr[$val].is_discontinued){$option.remove()}}})})}})});if(window.screen.width<=768){$('.woocommerce nav.woocommerce-pagination ul li a.prev').parent().addClass('arrow');$('.woocommerce nav.woocommerce-pagination ul li a.next').parent().addClass('arrow')}
$(window).load(function(){$('.account-item > a').on('click',function(){return!1});$('a').on('click',function(e){let $this=$(this);if($this.attr('href')!=undefined){let url=document.createElement('a');url.href=$this.attr('href');if(url.hash!=undefined&&url.hash){let $hash=url.hash;$hash=$hash.slice(1);let $element=$('[name='+$hash+']');let $additional=10;if($element.length>0){e.preventDefault();let $top=0,$header;if($hash=='ajax-change'){if(window.screen.width<=768){$header=$('#mobile-header').outerHeight(!0)}else{$header=$('#header').outerHeight(!0)}
$top=$('.woocommerce-shop-page').get(0).getBoundingClientRect().top+currentYPosition()-parseInt($header)-50}else{$header=$('#mobile-header').outerHeight(!0);$top=parseInt(($element.get(0).getBoundingClientRect().top+currentYPosition())-parseInt($header)-$additional)}
$('html, body').animate({scrollTop:$top},600,'easeOutCubic');return!1}}}})});window.product_search=0;$(document.body).on('focusin','.filter-for-mobile-content .product-search input[type=text]',function(){let $this=$(this);window.product_client_rect=this.getBoundingClientRect();window.product_search=$this.offset().top}).on('focusout','.filter-for-mobile-content .product-search input[type=text]',function(){if(window.product_search){$('html, body').animate({scrollTop:window.product_search-window.product_client_rect.top},100);window.product_search=0}});let $select=$('.woocommerce-ordering select[name="orderby"]');if($select.length>0){$(document.body).append('<select id="width_tmp_select"><option id="width_tmp_option"></option></select>');let $width_tmp_select=$('#width_tmp_select');$width_tmp_select.find("#width_tmp_option").html($select.find('option:selected').text());$select.width($width_tmp_select.width());$width_tmp_select=$('#width_tmp_select');$select.change(function(){$width_tmp_select.find("#width_tmp_option").html($(this).find('option:selected').text());$(this).width($width_tmp_select.width())})}
function goToElement($element){$('html, body').scrollTop(($element.get(0).getBoundingClientRect().top+currentYPosition())-parseInt($('#mobile-header').outerHeight(!0))-10)}
function textToSlug(text){return text.toString().toLowerCase().replace(/\s+/g,'-').replace(/[^\w\-]+/g,'').replace(/\-\-+/g,'-').replace(/^-+/,'').replace(/-+$/,'')}
function addNameAttrToHeaders(){$('body.enable-go-to-headers .page-content').find('h1, h2, h3, h4, h5, h6').each(function(){let $this=$(this);if(!$this.attr('name')){$this.attr('name',textToSlug($this.text()))}
$this.addClass('go-to-item')})}
$('.go-to-item').on('click',function(){let $this=$(this);window.location.hash=$this.attr('name');goToElement($this)});$('.woocommerce .quantity input.qty').on('focus',function(){let $this=$(this),$ul=$this.closest('.quantity').find('ul'),$boolean=!0,$woob_select_name=$this.closest('form').find('#woob_select_name'),$quantity=$this.closest('.quantity');if(window.inputClick){window.inputClick=!1}
$inputVal=$this.val();$this.addClass('focus-input');if($woob_select_name.length>0&&!$woob_select_name.val()){$boolean=!1}
if($quantity.length>0&&$boolean){let $discount=$quantity.find('.quantity-discount-table');if($discount.length>0){$discount.each(function(){let $this=$(this);if($this.data('variation-id')!=undefined){if($this.hasClass('variation')){$this.addClass('focus-active')}else{$this.removeClass('focus-active')}}else{$this.addClass('focus-active')}})}}
if($ul.length>0){$ul.each(function($key,$item){let $list_ul=$($item),$temp=$list_ul.closest('.focus-active');if($temp.length>0){showList($temp.find('li'),$inputVal)}})}
clearTimeout(window.focusInput)}).on('focusout',function(){let $this=$(this),$quantity=$this.closest('.quantity');if(!$this.val()){$this.val(1).trigger('change')}
if($quantity.length>0){let $discount=$quantity.find('.quantity-discount-table');if($discount.length>0){window.timerId=setTimeout(function(){$discount.removeClass('focus-active')},100)}}
window.focusInput=setTimeout(function(){$this.removeClass('focus-input')},500)});$('.qty-plus, .qty-minus').hover(function(){},function(){$(this).removeClass('active')});function set_cart_height(){let $clientHeight=document.body.clientHeight,$cart_height=$('#mobile-cart-wrap .bag-buttons').outerHeight(!0)+$('#mobile-cart-wrap .bag-total').outerHeight(!0)+$('#mobile-cart-wrap .bag-title').outerHeight(!0);if($(document.body).hasClass('admin-bar')){$cart_height+=$('#wpadminbar').outerHeight(!0)}
let $need=$clientHeight-$cart_height;$('#mobile-cart-wrap .bag-contents').css({"maxHeight":$need+"px","minHeight":$need+"px"})}
$(window).load(function(){set_cart_height()});$(document.body).on('wc_fragments_refreshed',function(){set_cart_height()});$(document.body).on('click_open_mini_cart',function(){set_cart_height()});$(document.body).on('added_to_cart',function(){set_cart_height()});$(window).resize(function(){set_cart_height()});$('body.single-product form.cart input.qty').on('change keyup',function(){let $this=$(this);let $ul=$this.closest('.quantity').find('ul');let $val=$this.val();if($ul.length>0){showList($ul.find('li'),$val)}
if(window.inputClick){$this.focus()}});$(document.body).on('click','.show-password-input',function(){let $this=$(this);let $parrent=$this.closest('.password-input');$parrent.find('.input-text').focus()});let $touchstart;window.setTimeout(function(){if($(document.body).hasClass('mobile-browser')||$(document.body).hasClass('ie-mobile')||$(document.body).hasClass('apple-mobile-browser')){$(document.body).on("touchstart click",'.for-ripple, .form-login .button, .quantity .qty-adjust a, .product_type_variable, .product_type_soldout, .add_to_cart_button, .extra-button.anchor-link, .load-more-btn, #container .button.woocommerce_waitlist',function(e){let $btn=$(this);if(!$btn.hasClass('loading')){if(e.type!='click'){$touchstart=setTimeout(function(){let x,y;if(e.type=='touchstart'||e.type=='touchmove'||e.type=='touchend'||e.type=='touchcancel'){let touch=e.originalEvent.touches[0]||e.originalEvent.changedTouches[0];x=touch.pageX;y=touch.pageY}else if(e.type=='mousedown'||e.type=='mouseup'||e.type=='mousemove'||e.type=='mouseover'||e.type=='mouseout'||e.type=='mouseenter'||e.type=='mouseleave'){x=e.clientX;y=e.clientY}
let $div=$('<div/>'),btnOffset=$btn.offset(),xPos=x-btnOffset.left,yPos=y-btnOffset.top;$div.addClass('ripple-effect');$div.css({height:$btn.height(),width:$btn.height(),top:yPos-($div.height()/2),left:xPos-($div.width()/2),background:$btn.data("ripple-color")||"#b6b6b6"});$btn.append($div);window.setTimeout(function(){$div.remove()},2000)},150)}
if(e.type=='click'&&$touchstart!=undefined&&$touchstart){clearTimeout($touchstart)}}});$(document.body).on("touchstart",'.sf-image-banner .image-banner-content .sf-button',function(e){let $this=$(this);$this.removeClass('touchend')});$(document.body).on("touchend touchcancel",'.sf-image-banner .image-banner-content .sf-button',function(e){let $this=$(this);$this.addClass('touchend')})}},0);$(".woocommerce-orders-table__row.order").on("click",".wcwl_remove_product",function(e){e.preventDefault();let $this=$(this),$block=$this.closest('.woocommerce-orders-table__row');if(wcwl_account!=undefined){$(".woocommerce-message, .woocommerce-error").remove();let t=$this.closest('.woocommerce-orders-table');t.block({message:null,overlayCSS:{background:'#fff',opacity:0.6}});let $action=typeof $this.data('action')!='undefined'?$this.data('action'):'wcwl_user_remove_self_waitlist',c={action:$action,product_id:$this.data("product-id"),user_id:wcwl_account.user_id,wcwl_remove_user_nonce:$this.data("nonce")};$.post(wcwl_account.ajaxurl,c,function(e){if(e.success){t.unblock();$block.remove();document.getElementById("wcwl_my_waitlist").scrollIntoView()}})}});$('form.variations_form').on('show_variation',function(event,data){const $table=$('.quantity-discount-table'),$block=$('.single_variation_wrap'),$form=$('.variations_form');if(data.is_in_stock==!0){$('.analysis-button-copy').remove();$block.find('a.button').show();$block.show();$form.find('table.variations select').css('margin-bottom','')}else{const $lab_button=jQuery('.single_variation_wrap').find('a.button').clone().addClass('analysis-button-copy').css('margin-bottom','14px').css('display','');if(!$('.waitlist .wcwl_hide input.wcwl_email').length){$lab_button.css('margin-left','0').insertAfter('.waitlist')}else{jQuery('.waitlist').find('.analysis-button-copy').remove();jQuery('.waitlist').css('display','flex');$lab_button.appendTo('.waitlist')}
$block.hide();$form.find('table.variations select').css('margin-bottom','0')}
if($table.length>0){$table.each(function(){var $this=$(this);if($this.data('variation-id')!=undefined&&$this.data('variation-id')==data.variation_id){$this.addClass('variation').removeClass('hide')}else{$this.removeClass('variation').addClass('hide')}})}});if(window.devicePixelRatio<2){if(window.devicePixelRatio==1){$(document.body).removeClass('wind10')}else{$(document.body).addClass('wind10')}}else{$(document.body).removeClass('wind10')}
function resizeDodument(){let screenCssPixelRatio=Math.abs(parseInt((1-(window.outerWidth/window.innerWidth))*100));if(screenCssPixelRatio>=10&&screenCssPixelRatio<48){$(document.body).removeClass('zoomNext zoom20').addClass('zoom10')}else if(screenCssPixelRatio>74){$(document.body).removeClass('zoomNext zoom10').addClass('zoom20')}else{$(document.body).removeClass('zoom10 zoom20').addClass('zoomNext')}}
$(window).on('resize',function(){if(typeof $resizeTimeout!=='undefined'){clearTimeout($resizeTimeout)}
if(window.devicePixelRatio<2){if(window.devicePixelRatio==1){$(document.body).removeClass('wind10')}else{$(document.body).addClass('wind10')}}else{$(document.body).removeClass('wind10')}
$resizeTimeout=setTimeout(function(){resizeDodument()},100)})});function showList($list,$val){var $i=0;if($list.length>0){$list.each(function(){var $this=jQuery(this);if($this.data('max')!=undefined){if($this.data('max')=='>'){$i++;if($i>3){$this.addClass('none')}else{$this.removeClass('none')}
if($i===1){$this.addClass('active')}else{$this.removeClass('active')}}else{if($val>$this.data('max')){$this.addClass('none')}else{$i++;if($i>3){$this.addClass('none')}else{$this.removeClass('none')}
if($i===1){$this.addClass('active')}else{$this.removeClass('active')}}}}else{if($this.hasClass('load_more')){if($i>3){$this.removeClass('none')}else{$this.addClass('none')}
if($i===1){$this.addClass('active')}else{$this.removeClass('active')}}}})}}