function currentYPosition(){if(self.pageYOffset)return self.pageYOffset;if(document.documentElement&&document.documentElement.scrollTop)
return document.documentElement.scrollTop;if(document.body.scrollTop)return document.body.scrollTop;return 0}
function cword(s){s=s.replace(/(?:\r\n|\r|\n)/g,' ');s=s.replace(/[^a-zA-ZА-Яа-яЁё0-9\s]/gi,"");s=s.replace(/(^\s*)|(\s*$)/gi,"");s=s.replace(/[ ]{2,}/gi," ");s=s.replace(/\n /,"\n");return s.split(' ').filter(function(str){return str!=""}).length}
let $inputVal=1,$boundingClientRect=[],$resizeTimeout;jQuery(document).ready(function($){const urlParams=new URLSearchParams(window.location.search),discount=urlParams.get('discount'),need=urlParams.get('need'),wpnonce=urlParams.get('wpnonce'),discount_url=urlParams.get('url');$(document).on({mouseenter:function(){if(!$(document.body).hasClass('mobile-browser')&&!$(document.body).hasClass('ie-mobile')&&!$(document.body).hasClass('apple-mobile-browser')){$(document.body).addClass('body-stop')}},mouseleave:function(){$(document.body).removeClass('body-stop')}},'ul.sub-menu, .multiselect-button .options');if(typeof ajaxurl!='undefined'&&discount&&need=='ajax'&&wpnonce){$.ajax({url:ajaxurl,global:!1,dataType:'json',method:'post',data:{discount:discount,wpnonce:wpnonce,action:'urlApplyCoupon',url:discount_url,},success:function(response){if(response.success){window.location.href=response.data.redirect}},error:function(){alert("Not found Data")}})}
function replaceCurrencySymbolByCountry(selector){var $element=typeof selector!=='undefined'?jQuery(selector):jQuery('body'),$priceAmount;if(cloudFlareGeoIp.getCountry()!=='US'){$element.find('.woocommerce-Price-amount .woocommerce-Price-currencySymbol').text('US$');$priceAmount=$element.find('.woocommerce-Price-amount').not(':has(.woocommerce-Price-currencySymbol)');$priceAmount.text($priceAmount.text().replace(/^\$/,'US$'))}}
cloudFlareGeoIp.onInit(function(){localStorage.setItem('shipping_widget_country_my',cloudFlareGeoIp.getCountry());replaceCurrencySymbolByCountry();jQuery(document.body).on('updated_checkout updated_wc_div wc_fragments_refreshed',function(){replaceCurrencySymbolByCountry()})});jQuery('body.single-product form.cart input.qty').on('change',function(){var $input=jQuery(this),qty=parseInt($input.val(),10),min=parseInt($input.attr('min'),10),max=parseInt($input.attr('max'),10);if(qty<min){$input.val(min)}else if(qty>max){$input.val(max)}});cloudFlareGeoIp.onInit(function(){localStorage.setItem('shipping_widget_country',cloudFlareGeoIp.getCountry());jQuery('.free-shipping-default, .free-shipping-non-usa, .free-shipping-usa').hide();if(cloudFlareGeoIp.getCountry()!=='US'){jQuery('.free-shipping-non-usa').show()}else{jQuery('.free-shipping-usa').show()}
jQuery('.global-widget-banner').css('opacity','1')});jQuery("#footer .widget_nav_menu .menu-item-has-children").each(function(){jQuery(this).append('<span class="plus"><i class="fa fa-chevron-down" aria-hidden="true"></i></spa>')});jQuery("#footer .widget_nav_menu .menu-item-has-children").on("click",'span, > a',function(e){let $width=jQuery(window).width();if($width<768){let $this=jQuery(this),$parent=$this.parent(),$arrow=$this.siblings('span');if($this.is('a')){$arrow=$this.siblings('span')}else{$arrow=$this}
$parent.toggleClass('active');$arrow.html($arrow.find('i').hasClass('fa-chevron-down')?'<i class="fa fa-chevron-up" aria-hidden="true"></i>':'<i class="fa fa-chevron-down" aria-hidden="true"></i>')}})});function getUrlParameterByName(name,url){if(!url)url=window.location.href;name=name.replace(/[\[\]]/g,"\\$&");var regex=new RegExp("[?&]"+name+"(=([^&#]*)|&|#|$)"),results=regex.exec(url);if(!results)return null;if(!results[2])return'';return decodeURIComponent(results[2].replace(/\+/g," "))}
function getCookie(name){var matches=document.cookie.match(new RegExp("(?:^|; )"+name.replace(/([\.$?*|{}\(\)\[\]\\\/\+^])/g,'\\$1')+"=([^;]*)"));return matches?decodeURIComponent(matches[1]):undefined}
jQuery(function($){addNameAttrToHeaders();$(window).load(function(){if(window.location.hash){let $hash=window.location.hash;if($hash){$hash=$hash.slice(1);let $element=$('[name='+$hash+']');if($element.length>0){let $header=$('#mobile-header').outerHeight(!0);$('html, body').scrollTop(($element.get(0).getBoundingClientRect().top+currentYPosition())-parseInt($header)-10)}}}});$(window).load(function(){$('.account-item > a').on('click',function(){return!1});$('a').on('click',function(e){let $this=$(this);if($this.attr('href')!=undefined){let url=document.createElement('a');url.href=$this.attr('href');if(url.hash!=undefined&&url.hash){let $hash=url.hash;$hash=$hash.slice(1);let $element=$('[name='+$hash+']');let $additional=10;if($element.length>0){e.preventDefault();let $header=$('#mobile-header').outerHeight(!0);let $top=parseInt(($element.get(0).getBoundingClientRect().top+currentYPosition())-parseInt($header)-$additional);window.scrollTo({top:$top,behavior:'smooth'});return!1}}}})});window.product_search=0;$(document.body).on('focusin','.filter-for-mobile-content .product-search input[type=text]',function(){let $this=$(this);window.product_client_rect=this.getBoundingClientRect();window.product_search=$this.offset().top}).on('focusout','.filter-for-mobile-content .product-search input[type=text]',function(){if(window.product_search){$('html, body').animate({scrollTop:window.product_search-window.product_client_rect.top},100);window.product_search=0}});let $select=$('.woocommerce-ordering select[name="orderby"]');if($select.length>0){$(document.body).append('<select id="width_tmp_select"><option id="width_tmp_option"></option></select>');let $width_tmp_select=$('#width_tmp_select');$width_tmp_select.find("#width_tmp_option").html($select.find('option:selected').text());$select.width($width_tmp_select.width());$width_tmp_select=$('#width_tmp_select');$select.change(function(){$width_tmp_select.find("#width_tmp_option").html($(this).find('option:selected').text());$(this).width($width_tmp_select.width())})}
function goToElement($element){$('html, body').scrollTop(($element.get(0).getBoundingClientRect().top+currentYPosition())-parseInt($('#mobile-header').outerHeight(!0))-10)}
function textToSlug(text){return text.toString().toLowerCase().replace(/\s+/g,'-').replace(/[^\w\-]+/g,'').replace(/\-\-+/g,'-').replace(/^-+/,'').replace(/-+$/,'')}
function addNameAttrToHeaders(){$('body.enable-go-to-headers .page-content').find('h1, h2, h3, h4, h5, h6').each(function(){let $this=$(this);if(!$this.attr('name')){$this.attr('name',textToSlug($this.text()))}
$this.addClass('go-to-item')})}
$('.go-to-item').on('click',function(){let $this=$(this);window.location.hash=$this.attr('name');goToElement($this)});$('.woocommerce .quantity input.qty').on('focus',function(){let $this=$(this),$ul=$this.closest('.quantity').find('ul'),$boolean=!0,$woob_select_name=$this.closest('form').find('#woob_select_name'),$quantity=$this.closest('.quantity');if(window.inputClick){window.inputClick=!1}
$inputVal=$this.val();$this.addClass('focus-input');if($woob_select_name.length>0&&!$woob_select_name.val()){$boolean=!1}
if($quantity.length>0&&$boolean){let $discount=$quantity.find('.quantity-discount-table');if($discount.length>0){$discount.each(function(){let $this=$(this);if($this.data('variation-id')!=undefined){if($this.hasClass('variation')){$this.addClass('focus-active')}else{$this.removeClass('focus-active')}}else{$this.addClass('focus-active')}})}}
if($ul.length>0){$ul.each(function($key,$item){let $list_ul=$($item),$temp=$list_ul.closest('.focus-active');if($temp.length>0){showList($temp.find('li'),$inputVal)}})}
clearTimeout(window.focusInput)}).on('focusout',function(){let $this=$(this),$quantity=$this.closest('.quantity');if(!$this.val()){$this.val(1).trigger('change')}
if($quantity.length>0){let $discount=$quantity.find('.quantity-discount-table');if($discount.length>0){window.timerId=setTimeout(function(){$discount.removeClass('focus-active')},100)}}
window.focusInput=setTimeout(function(){$this.removeClass('focus-input')},500)});$('.qty-plus, .qty-minus').hover(function(){},function(){$(this).removeClass('active')});function set_cart_height(){let $clientHeight=document.body.clientHeight,$cart_height=$('#mobile-cart-wrap .bag-buttons').outerHeight(!0)+$('#mobile-cart-wrap .bag-total').outerHeight(!0)+$('#mobile-cart-wrap .bag-title').outerHeight(!0);if($(document.body).hasClass('admin-bar')){$cart_height+=$('#wpadminbar').outerHeight(!0)}
let $need=$clientHeight-$cart_height;$('#mobile-cart-wrap .bag-contents').css({"maxHeight":$need+"px","minHeight":$need+"px"})}
$(window).load(function(){set_cart_height()});$(document.body).on('wc_fragments_refreshed',function(){set_cart_height()});$(document.body).on('click_open_mini_cart',function(){set_cart_height()});$(document.body).on('added_to_cart',function(){set_cart_height()});$(window).resize(function(){set_cart_height()});$('body.single-product form.cart input.qty').on('change keyup',function(){let $this=$(this);let $ul=$this.closest('.quantity').find('ul');let $val=$this.val();if($ul.length>0){showList($ul.find('li'),$val)}
if(window.inputClick){$this.focus()}});$(document.body).on('click','.show-password-input',function(){let $this=$(this);let $parrent=$this.closest('.password-input');$parrent.find('.input-text').focus()});let $touchstart;window.setTimeout(function(){if($(document.body).hasClass('mobile-browser')||$(document.body).hasClass('ie-mobile')||$(document.body).hasClass('apple-mobile-browser')){$(document.body).on("touchstart click",'.for-ripple, .form-login .button, .quantity .qty-adjust a, .product_type_variable, .product_type_soldout, .add_to_cart_button, .extra-button.anchor-link, .load-more-btn, #container .button.woocommerce_waitlist',function(e){let $btn=$(this);if(!$btn.hasClass('loading')){if(e.type!='click'){$touchstart=setTimeout(function(){let x,y;if(e.type=='touchstart'||e.type=='touchmove'||e.type=='touchend'||e.type=='touchcancel'){let touch=e.originalEvent.touches[0]||e.originalEvent.changedTouches[0];x=touch.pageX;y=touch.pageY}else if(e.type=='mousedown'||e.type=='mouseup'||e.type=='mousemove'||e.type=='mouseover'||e.type=='mouseout'||e.type=='mouseenter'||e.type=='mouseleave'){x=e.clientX;y=e.clientY}
let $div=$('<div/>'),btnOffset=$btn.offset(),xPos=x-btnOffset.left,yPos=y-btnOffset.top;$div.addClass('ripple-effect');$div.css({height:$btn.height(),width:$btn.height(),top:yPos-($div.height()/2),left:xPos-($div.width()/2),background:$btn.data("ripple-color")||"#b6b6b6"});$btn.append($div);window.setTimeout(function(){$div.remove()},2000)},150)}
if(e.type=='click'&&$touchstart!=undefined&&$touchstart){clearTimeout($touchstart)}}});$(document.body).on("touchstart",'.sf-image-banner .image-banner-content .sf-button',function(e){let $this=$(this);$this.removeClass('touchend')});$(document.body).on("touchend touchcancel",'.sf-image-banner .image-banner-content .sf-button',function(e){let $this=$(this);$this.addClass('touchend')})}},0);if(window.devicePixelRatio<2){if(window.devicePixelRatio==1){$(document.body).removeClass('wind10')}else{$(document.body).addClass('wind10')}}else{$(document.body).removeClass('wind10')}
function resizeDodument(){let screenCssPixelRatio=Math.abs(parseInt((1-(window.outerWidth/window.innerWidth))*100));if(screenCssPixelRatio>=10&&screenCssPixelRatio<48){$(document.body).removeClass('zoomNext zoom20').addClass('zoom10')}else if(screenCssPixelRatio>74){$(document.body).removeClass('zoomNext zoom10').addClass('zoom20')}else{$(document.body).removeClass('zoom10 zoom20').addClass('zoomNext')}}
$(window).on('resize',function(){if(typeof $resizeTimeout!=='undefined'){clearTimeout($resizeTimeout)}
if(window.devicePixelRatio<2){if(window.devicePixelRatio==1){$(document.body).removeClass('wind10')}else{$(document.body).addClass('wind10')}}else{$(document.body).removeClass('wind10')}
$resizeTimeout=setTimeout(function(){resizeDodument()},100)})});function showList($list,$val){var $i=0;if($list.length>0){$list.each(function(){var $this=jQuery(this);if($this.data('max')!=undefined){if($this.data('max')=='>'){$i++;if($i>3){$this.addClass('none')}else{$this.removeClass('none')}
if($i===1){$this.addClass('active')}else{$this.removeClass('active')}}else{if($val>$this.data('max')){$this.addClass('none')}else{$i++;if($i>3){$this.addClass('none')}else{$this.removeClass('none')}
if($i===1){$this.addClass('active')}else{$this.removeClass('active')}}}}else{if($this.hasClass('load_more')){if($i>3){$this.removeClass('none')}else{$this.addClass('none')}
if($i===1){$this.addClass('active')}else{$this.removeClass('active')}}}})}}