jQuery(document).ready(function(){let original_ratio=1,$body=jQuery('body'),isBundleProduct=jQuery('div.product.product-type-woosb').length>0,is_variable_product=!!jQuery('div.product.type-product').hasClass('product-type-variable'),qtySelector='.quantity:not(.not-focus) input.qty',priceSelector='#jckqv_summary .price .woocommerce-Price-amount, .product-price-wrap .woocommerce-Price-amount',delPriceSelector='#jckqv_summary .price del .woocommerce-Price-amount, .product-price-wrap del .woocommerce-Price-amount',insPriceSelector='#jckqv_summary .price ins .woocommerce-Price-amount, .product-price-wrap ins .woocommerce-Price-amount',originalPrice;function updatePrice(){let qty=parseInt(jQuery(this).val());if(qty>0){let newPrice=findPriceForQuantity(qty),ins_price=jQuery(insPriceSelector),del_price=jQuery(delPriceSelector);if(typeof newPrice!=='undefined'){let $replace=cloudFlareGeoIp.getCountry()!=='US'?'US$':'$';jQuery(priceSelector).each(function(){let $this=jQuery(this),$boolean=!0;if(is_variable_product&&!$this.closest('.woocommerce-variation-price').length)$boolean=!1;if(!$this.closest('h5.buy_more_text').length&&!$this.parent().is('del')&&$boolean){newPrice=parseFloat(newPrice.replace(new RegExp('[US$|$]+'),''));const totalPrice=(newPrice*qty).toFixed(2);$this.html($replace+totalPrice);addUnitsText($this,$replace,newPrice,qty)}});if(1!=original_ratio){if(typeof originalPrice==='undefined'){originalPrice=parseFloat(del_price.text().replace(new RegExp('[US$|$]+'),''))}
const salePrice=parseFloat(typeof newPrice==='string'?newPrice.replace(new RegExp('[US$|$]+'),''):newPrice);const totalPrice=(originalPrice*qty).toFixed(2);const totalSalePrice=(salePrice*qty).toFixed(2);if(del_price.length>0&&ins_price.length>0){del_price.html('<span class="woocommerce-Price-currencySymbol">'+$replace+'</span>'+totalPrice);ins_price.html('<span class="woocommerce-Price-currencySymbol">'+$replace+'</span>'+totalSalePrice)}else{del_price.html('<span class="woocommerce-Price-currencySymbol">'+$replace+'</span>'+totalSalePrice)}
addUnitsText(del_price,$replace,salePrice,qty)}}}}
function addUnitsText($price,currencySymbol,priceValue,qty){const $units=$('.product-price-wrap .price-units-text');if(qty<=1){if($units.length){$units.remove()}
return}
const unitsText=' ('+currencySymbol+priceValue+'/ea)';if($units.length){$units.html(unitsText)}else{$price.closest('.price').append('<span class="price-units-text">'+unitsText+'</span>')}}
function findPriceForQuantity(quantity){let trs;if(is_variable_product){trs=jQuery('.rp_wcdpd_pricing_table_variation:visible tr')}else{trs=jQuery('.rp_wcdpd_pricing_table tr')}
if(trs.length){return getPriceForQuantity(trs,quantity)}}
function getPriceForQuantity(trs,quantity){let labelRow=trs[0],pricesRow=trs[1];for(let i=0;i<labelRow.children.length;i++){let range=labelRow.children[i].innerText.split('-');if(range.length==1){let indexOfPlus=range[0].indexOf("+");if(indexOfPlus!==-1){range=range[0].substr(0,indexOfPlus);if(quantity>=parseInt(range)){return pricesRow.children[i].innerText}}else if(quantity==parseInt(range[0])){return pricesRow.children[i].innerText}}else if(range.length==2){if(quantity>=parseInt(range[0])&&quantity<=parseInt(range[1])){return pricesRow.children[i].innerText}}else{}}}
function attachEventHandlers(){$body.on('input',qtySelector,updatePrice);$body.on('change',qtySelector,updatePrice)}
function initDynamicPricing(){if(is_variable_product){delPriceSelector='.custom_single_variation del .woocommerce-Price-amount';insPriceSelector='.custom_single_variation ins .woocommerce-Price-amount'}
let jQdelPriceSelector=jQuery(delPriceSelector);if(0!==jQdelPriceSelector.length){let current_price=jQdelPriceSelector.text();current_price=current_price.replace(new RegExp('[US$|$]+'),''),discount_price=jQuery(insPriceSelector).text();discount_price=discount_price.replace(new RegExp('[US$|$]+'),'');original_ratio=discount_price/current_price}
jQuery(qtySelector).trigger('change')}
cloudFlareGeoIp.onInit(function(){const enabled=!$body.hasClass('woocommerce-cart')&&!isBundleProduct;if(enabled){attachEventHandlers();initDynamicPricing()}
jQuery(document).ajaxComplete(function(){if(jQuery('#jckqv').length!==0){initDynamicPricing()}})})})