/*!
* tingle.js
* @author  robin_parisi
* @version 0.13.2
* @url
*/
(function(root,factory){if(typeof define==='function'&&define.amd){define(factory)}else if(typeof exports==='object'){module.exports=factory()}else{root.tingle=factory()}}(this,function(){var transitionEvent=whichTransitionEvent();function Modal(options){var defaults={onClose:null,onOpen:null,beforeOpen:null,beforeClose:null,stickyFooter:!1,footer:!1,cssClass:[],closeLabel:'Close',closeMethods:['overlay','button','escape']};this.opts=extend({},defaults,options);this.init()}
Modal.prototype.init=function(){if(this.modal){return}
_build.call(this);_bindEvents.call(this);document.body.insertBefore(this.modal,document.body.firstChild);if(this.opts.footer){this.addFooter()}};Modal.prototype.destroy=function(){if(this.modal===null){return}
_unbindEvents.call(this);this.modal.parentNode.removeChild(this.modal);this.modal=null};Modal.prototype.open=function(){var self=this;if(typeof self.opts.beforeOpen==='function'){self.opts.beforeOpen()}
if(this.modal.style.removeProperty){this.modal.style.removeProperty('display')}else{this.modal.style.removeAttribute('display')}
this._scrollPosition=window.pageYOffset;document.body.classList.add('tingle-enabled');document.body.style.top=-this._scrollPosition+'px';this.setStickyFooter(this.opts.stickyFooter);this.modal.classList.add('tingle-modal--visible');if(transitionEvent){this.modal.addEventListener(transitionEvent,function handler(){if(typeof self.opts.onOpen==='function'){self.opts.onOpen.call(self)}
self.modal.removeEventListener(transitionEvent,handler,!1)},!1)}else{if(typeof self.opts.onOpen==='function'){self.opts.onOpen.call(self)}}
this.checkOverflow()};Modal.prototype.isOpen=function(){return!!this.modal.classList.contains("tingle-modal--visible")};Modal.prototype.close=function(){if(typeof this.opts.beforeClose==="function"){var close=this.opts.beforeClose.call(this);if(!close)return}
document.body.classList.remove('tingle-enabled');window.scrollTo(0,this._scrollPosition);document.body.style.top=null;this.modal.classList.remove('tingle-modal--visible');var self=this;if(transitionEvent){this.modal.addEventListener(transitionEvent,function handler(){self.modal.removeEventListener(transitionEvent,handler,!1);self.modal.style.display='none';if(typeof self.opts.onClose==="function"){self.opts.onClose.call(this)}},!1)}else{self.modal.style.display='none';if(typeof self.opts.onClose==="function"){self.opts.onClose.call(this)}}};Modal.prototype.setContent=function(content){if(typeof content==='string'){this.modalBoxContent.innerHTML=content}else{this.modalBoxContent.innerHTML="";this.modalBoxContent.appendChild(content)}
if(this.isOpen()){this.checkOverflow()}};Modal.prototype.getContent=function(){return this.modalBoxContent};Modal.prototype.addFooter=function(){_buildFooter.call(this)};Modal.prototype.setFooterContent=function(content){this.modalBoxFooter.innerHTML=content};Modal.prototype.getFooterContent=function(){return this.modalBoxFooter};Modal.prototype.setStickyFooter=function(isSticky){if(!this.isOverflow()){isSticky=!1}
if(isSticky){if(this.modalBox.contains(this.modalBoxFooter)){this.modalBox.removeChild(this.modalBoxFooter);this.modal.appendChild(this.modalBoxFooter);this.modalBoxFooter.classList.add('tingle-modal-box__footer--sticky');_recalculateFooterPosition.call(this);this.modalBoxContent.style['padding-bottom']=this.modalBoxFooter.clientHeight+20+'px'}}else if(this.modalBoxFooter){if(!this.modalBox.contains(this.modalBoxFooter)){this.modal.removeChild(this.modalBoxFooter);this.modalBox.appendChild(this.modalBoxFooter);this.modalBoxFooter.style.width='auto';this.modalBoxFooter.style.left='';this.modalBoxContent.style['padding-bottom']='';this.modalBoxFooter.classList.remove('tingle-modal-box__footer--sticky')}}};Modal.prototype.addFooterBtn=function(label,cssClass,callback){var btn=document.createElement("button");btn.innerHTML=label;btn.addEventListener('click',callback);if(typeof cssClass==='string'&&cssClass.length){cssClass.split(" ").forEach(function(item){btn.classList.add(item)})}
this.modalBoxFooter.appendChild(btn);return btn};Modal.prototype.resize=function(){console.warn('Resize is deprecated and will be removed in version 1.0')};Modal.prototype.isOverflow=function(){var viewportHeight=window.innerHeight;var modalHeight=this.modalBox.clientHeight;return modalHeight>=viewportHeight};Modal.prototype.checkOverflow=function(){if(this.modal.classList.contains('tingle-modal--visible')){if(this.isOverflow()){this.modal.classList.add('tingle-modal--overflow')}else{this.modal.classList.remove('tingle-modal--overflow')}
if(!this.isOverflow()&&this.opts.stickyFooter){this.setStickyFooter(!1)}else if(this.isOverflow()&&this.opts.stickyFooter){_recalculateFooterPosition.call(this);this.setStickyFooter(!0)}}}
function _recalculateFooterPosition(){if(!this.modalBoxFooter){return}
this.modalBoxFooter.style.width=this.modalBox.clientWidth+'px';this.modalBoxFooter.style.left=this.modalBox.offsetLeft+'px'}
function _build(){this.modal=document.createElement('div');this.modal.classList.add('tingle-modal');if(this.opts.closeMethods.length===0||this.opts.closeMethods.indexOf('overlay')===-1){this.modal.classList.add('tingle-modal--noOverlayClose')}
this.modal.style.display='none';this.opts.cssClass.forEach(function(item){if(typeof item==='string'){this.modal.classList.add(item)}},this);if(this.opts.closeMethods.indexOf('button')!==-1){this.modalCloseBtn=document.createElement('button');this.modalCloseBtn.classList.add('tingle-modal__close');this.modalCloseBtnIcon=document.createElement('span');this.modalCloseBtnIcon.classList.add('tingle-modal__closeIcon');this.modalCloseBtnIcon.innerHTML='×';this.modalCloseBtnLabel=document.createElement('span');this.modalCloseBtnLabel.classList.add('tingle-modal__closeLabel');this.modalCloseBtnLabel.innerHTML=this.opts.closeLabel;this.modalCloseBtn.appendChild(this.modalCloseBtnIcon);this.modalCloseBtn.appendChild(this.modalCloseBtnLabel)}
this.modalBox=document.createElement('div');this.modalBox.classList.add('tingle-modal-box');this.modalBoxContent=document.createElement('div');this.modalBoxContent.classList.add('tingle-modal-box__content');this.modalBox.appendChild(this.modalBoxContent);if(this.opts.closeMethods.indexOf('button')!==-1){this.modal.appendChild(this.modalCloseBtn)}
this.modal.appendChild(this.modalBox)}
function _buildFooter(){this.modalBoxFooter=document.createElement('div');this.modalBoxFooter.classList.add('tingle-modal-box__footer');this.modalBox.appendChild(this.modalBoxFooter)}
function _bindEvents(){this._events={clickCloseBtn:this.close.bind(this),clickOverlay:_handleClickOutside.bind(this),resize:this.checkOverflow.bind(this),keyboardNav:_handleKeyboardNav.bind(this)};if(this.opts.closeMethods.indexOf('button')!==-1){this.modalCloseBtn.addEventListener('click',this._events.clickCloseBtn)}
this.modal.addEventListener('mousedown',this._events.clickOverlay);window.addEventListener('resize',this._events.resize);document.addEventListener("keydown",this._events.keyboardNav)}
function _handleKeyboardNav(event){if(this.opts.closeMethods.indexOf('escape')!==-1&&event.which===27&&this.isOpen()){this.close()}}
function _handleClickOutside(event){if(this.opts.closeMethods.indexOf('overlay')!==-1&&!_findAncestor(event.target,'tingle-modal')&&event.clientX<this.modal.clientWidth){this.close()}}
function _findAncestor(el,cls){while((el=el.parentElement)&&!el.classList.contains(cls));return el}
function _unbindEvents(){if(this.opts.closeMethods.indexOf('button')!==-1){this.modalCloseBtn.removeEventListener('click',this._events.clickCloseBtn)}
this.modal.removeEventListener('mousedown',this._events.clickOverlay);window.removeEventListener('resize',this._events.resize);document.removeEventListener("keydown",this._events.keyboardNav)}
function extend(){for(var i=1;i<arguments.length;i++){for(var key in arguments[i]){if(arguments[i].hasOwnProperty(key)){arguments[0][key]=arguments[i][key]}}}
return arguments[0]}
function whichTransitionEvent(){var t;var el=document.createElement('tingle-test-transition');var transitions={'transition':'transitionend','OTransition':'oTransitionEnd','MozTransition':'transitionend','WebkitTransition':'webkitTransitionEnd'};for(t in transitions){if(el.style[t]!==undefined){return transitions[t]}}}
return{modal:Modal}}))