jQuery(function($){let $body=$('body'),bundledProducts=[],$bundle=$('.woosb-products'),discount=parseFloat($bundle.data('discount')),discountAmount=parseFloat($bundle.data('discount-amount')),fixedPrice=$bundle.data('fixed-price'),$quantity=$('div.product form.cart div.quantity'),$form=$quantity.closest('form'),priceFrom=[];function initQuantityDiscountTable(){$('.quantity-discount-table').hover(function(){$(this).addClass('hover-active')},function(){$(this).removeClass('hover-active')});$('.quantity-discount-table').on('click','.load_more',function(){var $this=$(this),$ul=$this.closest('ul'),$block=$this.closest('.quantity'),$input=$block.find('input[name="quantity"]'),$val=$input.val(),$i=0,$boolean=!0;$val=($val?$val:1);$input.focus();if($ul.length>0){$ul.find('li').each(function(){if($val<=$(this).data('from')&&$(this).hasClass('none')&&$i<=2&&!$(this).data('show')){$(this).data('show',1).attr('show',1);$(this).removeClass('none');$i++}else if($(this).data('show')){$(this).removeClass('none')}else if($(this).hasClass('none')){$boolean=!1}else if(!$(this).hasClass('load_more')&&!$(this).hasClass('none')){$boolean=!0}})}
clearTimeout(window.timerId);if($boolean){$this.addClass('none');$ul.find('li').each(function(){$(this).data('show',0).attr('show',0)})}});$('.quantity-discount-table li').on('click',function(){var $this=$(this);if($this.data('from')!=undefined){var $quantity=$this.closest('.quantity');if($quantity.length>0){$quantity.find('input[name="quantity"]').val($this.data('from')).change();$quantity.find('input[name="quantity"]').focus();clearTimeout(window.timerId);$('.quantity-discount-table').addClass('focus-active')}}})}
function initVolumePricing($val){let basePrice=0;bundledProducts=[];$('.woosb-product').each(function(){let $product=$(this);bundledProducts.push({id:$product.data('id'),price:$product.data('price'),qty:$product.data('qty'),volumePricing:$product.data('volume_pricing')})});bundledProducts.forEach(function(bundledProduct){if(bundledProduct.volumePricing){bundledProduct.volumePricing.forEach(function($item,$index){priceFrom[$item.from]=[]})}});priceFrom.forEach(function($item,$index){priceFrom.some(function($price_item,$price_index){if($index<$price_index){priceFrom[$index]={full_price:0,price:0,minimum:$price_index-1};return!0}});if(typeof priceFrom[$index].price=='undefined'){priceFrom[$index]={full_price:0,price:0,minimum:''}}});priceFrom.forEach(function($price_item,$price_index){bundledProducts.forEach(function(bundledProduct,$bundled_index){if(bundledProduct.volumePricing){bundledProduct.volumePricing.some(function($item,$index){if(bundledProduct.qty){if($price_index>=$item.from){let $price=$item.price,$calculateSale=calculateSalePrice($item.price,discountAmount,discount,fixedPrice,bundledProducts[$bundled_index].price);priceFrom[$price_index].full_price+=$price;priceFrom[$price_index].price+=$calculateSale;return!0}}})}else{let $price=bundledProduct.price,$calculateSale=calculateSalePrice(bundledProduct.price,discountAmount,discount,fixedPrice,bundledProducts[$bundled_index].price);priceFrom[$price_index].full_price+=$price;priceFrom[$price_index].price+=$calculateSale}})});if(priceFrom.length){let $text='<div class="quantity-discount-table">'+'<ul>',$price_bundle='';priceFrom.forEach(function($item,$index){let $itemprice=$item.price.toFixed(2);basePrice=!basePrice?$itemprice:basePrice;$text+='<li data-from="'+$index+'" data-price="'+$itemprice+'" data-max="'+$item.minimum+'">'+'<div class="range">'+$index+' '+($index>1?'+':'')+'</div>'+'<div class="info'+($index>1?' red':'')+'">'+'<div><span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">'+(localStorage.getItem('geo_country')!='US'?'US':'')+'$</span>'+$itemprice+'</bdi></span>/ea</div>'+($index>1?'<p>Save '+Math.ceil(((basePrice-$itemprice)/$itemprice)*100)+'%</p>':'')+'</div>'+'</li>';$price_bundle='<span class="woocommerce-Price-amount amount"><bdi><span class="woocommerce-Price-currencySymbol">'+(localStorage.getItem('geo_country')!='US'?'US':'')+'</span>'+$itemprice+'</bdi></span>'});$text+='<li class="load_more">Show More</li>'+'</ul>'+'</div>';if($price_bundle){$('.buy_more_text span.variable-mix').html($price_bundle)}
$('.product-price-wrap').removeClass('hide');if(basePrice>0){if($form.find('select').length>0&&!$form.find('select').val()){$form.find('button').addClass('disabled')}else{if(!$form.find('button').hasClass('approval-needed')){$form.find('button').removeClass('disabled')}}
$('.buy_more_text').removeClass('hideme');$quantity.append($text)}}else{$('.buy_more_text').addClass('hide')}
if(typeof $val!='undefined'&&$val&&basePrice<=0){$('.product-price-wrap').addClass('hide');if(!$form.find('button').hasClass('approval-needed')){$form.find('button').addClass('disabled')}
$('.buy_more_text').addClass('hideme')}}
function init($val){if($bundle.length){initVolumePricing($val)}
initQuantityDiscountTable()}
function formatPrice(price){let formattedPrice=price.toString(),pos=formattedPrice.indexOf('.'),$return=0;if(pos!==-1){formattedPrice=formattedPrice.slice(0,pos+3)}
$return=parseFloat(formattedPrice).toFixed(2);return $return}
function calculateSalePrice(price,discountAmount,discount,fixedPrice,first_price){let salePrice;if(fixedPrice==='no'){if(discountAmount>0){salePrice=price-discountAmount}else if(discount>0&&discount<100){salePrice=parseFloat((Math.round((price*(100-discount)/100)*100)/100).toFixed(2))}else{salePrice=price}}else{salePrice=price}
return salePrice}
function updatePrice(){let $qty=$(this),$bundle=$('.woosb-products'),discount=parseFloat($bundle.data('discount')),discountAmount=parseFloat($bundle.data('discount-amount')),fixedPrice=$bundle.data('fixed-price'),qty=$qty.val(),currencySymbol=$('.product-price-wrap .woocommerce-Price-amount .woocommerce-Price-currencySymbol').html(),currencySymbolTag='<span class="woocommerce-Price-currencySymbol">'+currencySymbol+'</span>',salePrice={};if(qty<=0){return}
bundledProducts.forEach(function(bundledProduct){let $productPriceWrapper=$('.woosb-product[data-id='+bundledProduct.id+'] .woosb-price-ori'),productPrice,productSalePrice;if(bundledProduct.volumePricing.length>0){for(let i=0;i<bundledProduct.volumePricing.length;i++){if(qty>=bundledProduct.volumePricing[i].from){productPrice=bundledProduct.volumePricing[i].price;break}}}else{productPrice=bundledProduct.price}
productPrice=parseFloat(productPrice);if($productPriceWrapper.length>0){productSalePrice=calculateSalePrice(productPrice,0,discount,fixedPrice,bundledProduct.price);$productPriceWrapper.find('> .woocommerce-Price-amount').html(currencySymbolTag+formatPrice(productPrice));$productPriceWrapper.find('> del > .woocommerce-Price-amount').html(currencySymbolTag+formatPrice(productPrice));$productPriceWrapper.find('> ins > .woocommerce-Price-amount').html(currencySymbolTag+formatPrice(productSalePrice))}});priceFrom.some(function($item,$index){if($item.minimum&&qty<=$item.minimum){salePrice.price=$item.price.toFixed(2);salePrice.full_price=$item.full_price.toFixed(2);return!0}else if(!$item.minimum&&qty>0){salePrice.price=$item.price.toFixed(2);salePrice.full_price=$item.full_price.toFixed(2);return!0}});let $price_wrap=$('.product-price-wrap'),$price=$price_wrap.find('.price');if(typeof $price.data('min')!="undefined"){let $select_name=$('#woob_select_name');if($select_name.length>0){if($select_name.val()){$price.html('<del><span class="woocommerce-Price-amount amount">'+currencySymbolTag+salePrice.full_price+'</span></del> <ins><span class="woocommerce-Price-amount amount">'+currencySymbolTag+salePrice.price+'</span></ins>')}else{$price.html('<span class="woocommerce-Price-amount amount"><bdi>'+currencySymbolTag+$price.data('min')+'</bdi></span> – <span class="woocommerce-Price-amount amount"><bdi>'+currencySymbolTag+$price.data('max')+'</bdi></span>')}}}else{let unitPrice;if(typeof salePrice.price!='undefined'){unitPrice=salePrice.price;$price_wrap.find('.woocommerce-Price-amount').html(currencySymbolTag+(salePrice.price*qty).toFixed(2))}
if(typeof salePrice.full_price!='undefined'){unitPrice=salePrice.full_price;$price_wrap.find('del .woocommerce-Price-amount').html(currencySymbolTag+(salePrice.full_price*qty).toFixed(2))}
if(typeof salePrice.price!='undefined'){unitPrice=salePrice.price;$price_wrap.find('ins .woocommerce-Price-amount').html(currencySymbolTag+(salePrice.price*qty).toFixed(2))}
if(typeof unitPrice!=='undefined'){addUnitsText($price,currencySymbolTag,unitPrice,qty)}}}
function addUnitsText($price,currencySymbol,priceValue,qty){const $units=$price.find('.price-units-text');if(qty<=1){if($units.length){$units.remove()}
return}
const unitsText=' ('+currencySymbol+priceValue+'/ea)';if($units.length){$units.html(unitsText)}else{$price.append('<span class="price-units-text">'+unitsText+'</span>')}}
init();$('.variations.select_name select').on('change',function(){let $this_select=$(this),$json=$this_select.data('json'),$qty=$('.single-product .summary .quantity input.qty'),$boolean=!1,$min=null;if($this_select.val()){if(!$('.add_to_cart_button').hasClass('approval-needed')){$('.add_to_cart_button').removeClass('disabled')}
$('.woosb-bundled').removeClass('hide');$('.quantity-discount-table').removeClass('hide');$('.buy_more_text').removeClass('hide')}else{$('.add_to_cart_button').addClass('disabled');$('.woosb-bundled').addClass('hide');$('.quantity-discount-table').addClass('hide');$('.buy_more_text').addClass('hide')}
$('.woosb-wrap .woosb-products .woosb-product').each(function(){let $this=$(this);if($this_select.val()&&typeof $json[$this_select.val()][$this.data('parent-id')]!='undefined'&&typeof $json[$this_select.val()][$this.data('parent-id')].stock!='undefined'){let $stock=$json[$this_select.val()][$this.data('parent-id')].stock;if($min===null&&$stock){$min=$stock}else if($min>$stock&&$stock){$min=$stock}}
if($this_select.val()&&typeof $json[$this_select.val()][$this.data('parent-id')]!='undefined'&&$json[$this_select.val()][$this.data('parent-id')].content){$this.replaceWith($json[$this_select.val()][$this.data('parent-id')].content);$boolean=!0}});if($min!==null){$qty.attr('max',$min);$qty.trigger('change')}
if($boolean){$('.quantity-discount-table').remove()}
init($this_select.val());$('.woocommerce .quantity input.qty').trigger('change');let $error=$('.woocommerce-error');if($error.length>0){$error.remove()}});if($bundle.length){$body.on('input change','.quantity:not(.not-focus) input.qty',updatePrice)}})